'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Windowed_OS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _10_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _10_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _10_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _10_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1systemsettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1systemsettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2apps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2apps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3personalize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3personalize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5development() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5development", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ace_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ace_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ace_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ace_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ace_of_hearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ace_of_hearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ace_of_spades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ace_of_spades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ace_of_spades2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ace_of_spades2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1257\deff0\deflang1061{\fonttbl{\f0\fnil\fcharset0 Segoe UI Light;}{\f1\fnil\fcharset186 Segoe UI;}{\f2\fnil\fcharset186 Calibri;}{\f3\fnil\fcharset0 Calibri;}{\f4\fnil\fcharset186 MS Shell Dlg 2;}{\f5\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red0\green77\blue187;}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qr\lang1033\f0\fs16 Windowed OS Documentation\line\fs28\par
        '''\pard\sa200\sl276\slmult1\cf1\lang1061\ul\f1\fs40 Windowed OS documentation\par
        '''\cf0\ulno [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CalculatorDocs() As String
            Get
                Return ResourceManager.GetString("CalculatorDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property canvas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canvas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clickit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clickit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property colors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cpu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ::downloads the latest firmware from internet
        '''cd &quot;%appdata%\Windowed Technologies Ltd\Windowed OS\1.1.2.0\Windowed&quot;
        '''set /p server=&lt;server.txt
        '''wget --no-check-certificate &quot;%server%&quot; -O dload.exe
        '''del server.txt
        '''pause.
        '''</summary>
        Friend ReadOnly Property dload() As String
            Get
                Return ResourceManager.GetString("dload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property docs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("docs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1257\deff0\deflang1061{\fonttbl{\f0\fnil\fcharset0 Segoe UI Light;}{\f1\fnil\fcharset186 Segoe UI;}{\f2\fnil\fcharset186 Calibri;}{\f3\fnil\fcharset0 Calibri;}{\f4\fnil\fcharset186 MS Shell Dlg 2;}{\f5\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red0\green77\blue187;}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qr\lang1033\f0\fs16 Windowed OS Documentation\line\fs28\par
        '''\pard\sa200\sl276\slmult1\cf1\lang1061\ul\f1\fs40 Windowed OS documentation\par
        '''\cf0\ulno [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Documentation() As String
            Get
                Return ResourceManager.GetString("Documentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ::downloads and starts upgrader, which downloads the update
        '''cd &quot;%appdata%\Windowed Technologies Ltd\Windowed OS\1.1.2.0\Windowed&quot;
        '''wget --no-check-certificate &quot;https://docs.google.com/uc?export=download&amp;id=1Ht4Y9sy74gJPV1piW9oRiyXQrA0Y21zR&quot; -O upgrader.bat 2&gt;nul
        '''start upgrader.bat
        '''del %0 /Y &gt;nul
        '''exit
        '''.
        '''</summary>
        Friend ReadOnly Property download_upgrader() As String
            Get
                Return ResourceManager.GetString("download_upgrader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1257\deff0\deflang1061{\fonttbl{\f0\fnil\fcharset0 Segoe UI Light;}{\f1\fnil\fcharset186 Segoe UI;}{\f2\fnil\fcharset186 Calibri;}{\f3\fnil\fcharset0 Calibri;}{\f4\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red0\green77\blue187;\red255\green0\blue0;}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qr\lang1033\f0\fs16 Windowed OS Documentation\line\fs28\par
        '''\pard\sa200\sl276\slmult1\cf1\lang1061\ul\f1\fs40 Windowed OS documentation\par
        '''\cf0\ulnone\b\fs24 Image D [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DrawDocs() As String
            Get
                Return ResourceManager.GetString("DrawDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property errror10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("errror10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property errror9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("errror9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f16929280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f16929280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f22272576() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f22272576", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FirmwareUpdater() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FirmwareUpdater", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fonts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fonts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jack_of_clubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jack_of_clubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jack_of_clubs2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jack_of_clubs2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jack_of_diamonds2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jack_of_diamonds2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jack_of_hearts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jack_of_hearts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jack_of_spades2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jack_of_spades2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property king_of_clubs2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king_of_clubs2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property king_of_diamonds2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king_of_diamonds2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property king_of_hearts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king_of_hearts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property king_of_spades2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("king_of_spades2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property load() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property lock9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("lock9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1257\deff0\deflang1061{\fonttbl{\f0\fnil\fcharset0 Segoe UI Light;}{\f1\fnil\fcharset186 Segoe UI;}{\f2\fnil\fcharset186 Calibri;}{\f3\fnil\fcharset0 Calibri;}{\f4\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red0\green77\blue187;}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qr\lang1033\f0\fs16 Windowed OS Documentation\line\fs28\par
        '''\pard\sa200\sl276\slmult1\cf1\lang1061\ul\f1\fs40 Windowed OS documentation\par
        '''\cf0\ulnone\b\fs24 Media player\par
        '''\b0\f2\fs2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MediaPlayerDocs() As String
            Get
                Return ResourceManager.GetString("MediaPlayerDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1257\deff0\deflang1061{\fonttbl{\f0\fnil\fcharset0 Segoe UI Light;}{\f1\fnil\fcharset186 Segoe UI;}{\f2\fnil\fcharset186 Calibri;}{\f3\fnil\fcharset0 Calibri;}{\f4\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red0\green77\blue187;}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qr\lang1033\f0\fs16 Windowed OS Documentation\line\fs28\par
        '''\pard\sa200\sl276\slmult1\cf1\lang1061\ul\f1\fs40 Windowed OS documentation\par
        '''\cf0\ulnone\b\fs24 Rich Text Notepad\par
        '''\b0\f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NotepadDocs() As String
            Get
                Return ResourceManager.GetString("NotepadDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pictureviewer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pictureviewer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property pitch1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("pitch1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property pitch2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("pitch2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property pitch3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("pitch3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property pitch4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("pitch4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property power1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_of_clubs2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_of_clubs2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_of_diamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_of_diamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_of_diamonds2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_of_diamonds2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_of_hearts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_of_hearts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property queen_of_spades2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_of_spades2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scoreboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scoreboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property shutdown10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("shutdown10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property shutdown11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("shutdown11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property shutdown9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("shutdown9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property simon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("simon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sleep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sleep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sleep9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sleep9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startup1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startup3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property startup4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property startup9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("startup9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property texture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("texture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ttt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ttt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property unlock9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("unlock9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ::lets Windowed OS know if there is an update available
        '''cd &quot;%appdata%\Windowed Technologies Ltd\Windowed OS\1.1.2.0\Windowed&quot;
        '''set /p server=&lt;server.txt
        '''wget --no-check-certificate &quot;%server%&quot; -O version.txt 2&gt;nul
        '''del server.txt.
        '''</summary>
        Friend ReadOnly Property update_check() As String
            Get
                Return ResourceManager.GetString("update_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_aqua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_aqua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_violet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_violet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property voide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property wake_up9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("wake_up9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property web_explorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("web_explorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property wget() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("wget", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property windowed_close() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windowed_close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property windowed_ding() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windowed_ding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property windowed_error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windowed_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property windowed_exclamation() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windowed_exclamation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property windowed_os() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windowed_os", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property windowed_process() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("windowed_process", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
