Public Class BIOS


    Private Sub BIOS_KeyDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Keys.NumPad1 Then
            Exit Sub
        ElseIf e.KeyCode = Keys.NumPad2 Then
            Label7.Visible = False
            Label6.Visible = False
            If Not My.Computer.FileSystem.DirectoryExists(My.Computer.FileSystem.SpecialDirectories.CurrentUserApplicationData & "\Windowed") Then My.Computer.FileSystem.CreateDirectory(My.Computer.FileSystem.SpecialDirectories.CurrentUserApplicationData & "\Windowed")
            My.Computer.FileSystem.WriteAllText(My.Computer.FileSystem.SpecialDirectories.CurrentUserApplicationData & "\Windowed\test.txt", "This is a test file generated by the BIOS", False, System.Text.Encoding.ASCII)
            If My.Computer.FileSystem.FileExists(My.Computer.FileSystem.SpecialDirectories.CurrentUserApplicationData & "\Windowed\test.txt") Then Label8.Text = "Test results:" & vbNewLine & "Success"
            If Not My.Computer.FileSystem.FileExists(My.Computer.FileSystem.SpecialDirectories.CurrentUserApplicationData & "\Windowed\test.txt") Then Label8.Text = "Test results:" & vbNewLine & "Fail"
            My.Computer.FileSystem.DeleteFile(My.Computer.FileSystem.SpecialDirectories.CurrentUserApplicationData & "\Windowed\test.txt")
            Label8.Visible = True
        ElseIf e.KeyCode = Keys.NumPad3 Then
            Label6.Visible = False
            Label8.Visible = False
            Label7.Visible = True
        ElseIf e.KeyCode = Keys.NumPad4 Then
            Label7.Visible = False
            Label8.Visible = False
            Label6.Visible = True
        ElseIf e.KeyCode = Keys.Y Then
            If Label6.Visible = True Then
                Me.DialogResult = Windows.Forms.DialogResult.OK
                Me.Close()
            End If
        ElseIf e.KeyCode = Keys.N Then
            If Label6.Visible = True Then
                Me.DialogResult = Windows.Forms.DialogResult.Cancel
                Me.Close()
            End If
        ElseIf e.KeyCode = Keys.C Then
            If Label6.Visible = True Then
                Label6.Visible = False
            End If
        ElseIf e.KeyCode = Keys.Enter Then
            Label7.Visible = False
            Label8.Visible = False
            If Label6.Visible = True Then
                Me.DialogResult = Windows.Forms.DialogResult.OK
                Me.Close()
            End If
        ElseIf e.KeyCode = Keys.Escape Then
            Me.DialogResult = Windows.Forms.DialogResult.Cancel
            Me.Close()
        End If

    End Sub
End Class